version: '3'
services:
   darknet:
      volumes:
         - /usr/lib64/libnvidia-ptxjitcompiler.so.1:/usr/lib/libnvidia-ptxjitcompiler.so.1
         - /usr/lib64/libcuda.so.1:/usr/lib/libcuda.so.1
         - /usr/lib64/libnvidia-fatbinaryloader.so.384.81:/usr/lib/libnvidia-fatbinaryloader.so.384.81
      devices:
         - /dev/nvidia0:/dev/nvidia0
         - /dev/nvidiactl:/dev/nvidiactl
         - /dev/nvidia-uvm:/dev/nvidia-uvm
         - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
      stdin_open: true
      tty: true
      image: darknet:latest
      command: ["train"]
      ports:
         - "8080:8080"
